_target_: mayavoz.data.dataset.MayaDataset
name : dns-2020
root_dir : /Users/shahules/Myprojects/MS-SNSD
duration : 2.0
sampling_rate: 16000
batch_size: 32
min_valid_minutes: 15
files:
  train_clean : CleanSpeech_training
  test_clean : CleanSpeech_training
  train_noisy : NoisySpeech_training
  test_noisy : NoisySpeech_training
