_target_: enhancer.models.demucs.Demucs
num_channels: 1
resample: 4
sampling_rate : 16000

encoder_decoder:
  depth: 4
  initial_output_channels: 64
  kernel_size: 8
  stride: 4
  growth_factor: 2
  glu: True

lstm:
  bidirectional: False
  num_layers: 2
